# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: debug-statements
    -   id: check-ast
        language_version: python3
-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.3.4
    hooks:
        # Run the linter.
    -   id: ruff
        args: [ --fix ]
        # Run the formatter.
    -   id: ruff-format
# export python requirements
# LINUX 3.8
-   repo: https://github.com/pdm-project/pdm
    rev: 2.20.1
    hooks:
      - id: pdm-export
        name: pdm-export-py38unix
        args: ['-o', 'requirements/requirementspy38unix.txt', '--without-hashes', '-L', 'pdm-py38unix.lock']
        files: ^pdm-py38unix.lock$
# LINUX 3.9+
-   repo: https://github.com/pdm-project/pdm
    rev: 2.20.1
    hooks:
      - id: pdm-export
        name: pdm-export-py39+unix
        args: ['-o', 'requirements/requirementspy39+unix.txt', '--without-hashes', '-L', 'pdm-py39+unix.lock']
        files: ^pdm-py39\+unix.lock$
# WINDOWS 3.8
-   repo: https://github.com/pdm-project/pdm
    rev: 2.20.1
    hooks:
      - id: pdm-export
        name: pdm-export-py38win
        args: ['-o', 'requirements/requirementspy38win.txt', '--without-hashes', '-L', 'pdm-py38win.lock']
        files: ^pdm-py38win.lock$
# WINDOWS 3.9+
-   repo: https://github.com/pdm-project/pdm
    rev: 2.20.1
    hooks:
      - id: pdm-export
        name: pdm-export-py39+win
        args: ['-o', 'requirements/requirementspy39+win.txt', '--without-hashes', '-L', 'pdm-py39+win.lock']
        files: ^pdm-py39\+win.lock$
# MACOS 3.8
-   repo: https://github.com/pdm-project/pdm
    rev: 2.20.1
    hooks:
      - id: pdm-export
        name: pdm-export-py38mac
        args: ['-o', 'requirements/requirementspy38mac.txt', '--without-hashes', '-L', 'pdm-py38macos.lock']
        files: ^pdm-py38macos.lock$
# MACOS 3.9+
-   repo: https://github.com/pdm-project/pdm
    rev: 2.20.1
    hooks:
      - id: pdm-export
        name: pdm-export-py39\+mac
        args: ['-o', 'requirements/requirementspy39+mac.txt', '--without-hashes', '-L', 'pdm-py39+macos.lock']
        files: ^pdm-py39\+macos.lock$

#     # Mypy
# -   repo: https://github.com/pre-commit/mirrors-mypy
#     rev: v1.9.0
#     hooks:
#     -   id: mypy
#         args: [--python-version=38, --ignore-missing-imports, --explicit-package-bases, ]
