[tox]
envlist = py310, py311, py312, py313, py314
requires = tox-uv

[testenv]
extras = all
deps =
    pytest>=7.4.4
commands =
    pytest

[testenv:headless]
extras =
deps =
    pytest>=7.4.4
commands =
    pytest tests_headless/
