name: Test Pyoma2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false  # Continue running jobs even if a previous job fails
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
        os: [ubuntu-latest, windows-latest, macos-latest]
        exclude:
          - os: macos-latest
            python-version: "3.8"

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install tkinter for Ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get install -y python3-tk

    - name: Install dependencies
      run: uv sync --group qa

    - name: Run tests
      run: uv run pytest
      continue-on-error: false

    - name: Set job status
      if: failure()
      run: echo "job_status=failure" >> $GITHUB_ENV
      shell: bash

  check_failures:
    needs: [test]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Check for failures
        run: |
          if [[ "${{ contains(needs.*.result, 'failure') }}" == "true" ]]; then
            echo "One or more jobs failed"
            exit 1
          else
            echo "All jobs succeeded"
          fi
